language: c
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 20 brew install cmocka android-ndk; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install-cmocka-linux.sh; fi
android:
  components:
    - ndk
script:
  - make && make -C bindings/go && make -C bindings/go test && make test
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
matrix:
  include:
    - os: osx
      compiler: arm-linux-androideabi-gcc
      env: NDKROOT=/usr/local/opt/android-ndk TOOLCHAINPATH=$NDKROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin PATH=$TOOLCHAINPATH:$PATH SYSROOT=$NDKROOT/platforms/android-24/arch-arm
