language: c
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  brew install cmocka; fi
  - if [[ ! -z "$NDKROOT" ]]; then travis_wait 20 brew install android-ndk; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install-cmocka-linux.sh; fi
script:
  - make && make -C bindings/go && make -C bindings/go test && make test
#compiler:
#  - clang
#  - gcc
#os:
#  - linux
#  - osx
matrix:
  include:
    - os: osx
      compiler: arm-linux-androideabi-gcc
      env: NDKROOT=/usr/local/Cellar/android-ndk/r13b PATH=$NDKROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:$PATH SYSROOT=$NDKROOT/platforms/android-24/arch-arm
