language: c
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install-cmocka-linux.sh; fi
script:
  - make && make -C bindings/go && make -C bindings/go test && make test
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CFLAGS="-m32" LDFLAGS="-m32" LDFLAGS_STATIC="-m32" UNICORN_QEMU_FLAGS="--cpu=i386"
    - os: linux
      compiler: clang
      env: CFLAGS="-m32" LDFLAGS="-m32" LDFLAGS_STATIC="-m32" UNICORN_QEMU_FLAGS="--cpu=i386"
    - if: branch = master
      os: osx
      script: brew install --HEAD unicorn && brew test unicorn
      compiler: gcc
    - if: branch = master
      os: osx
      script: brew install --HEAD unicorn && brew test unicorn
      compiler: clang
  allow_failures:
    - os: osx
      script: brew install --HEAD unicorn && brew test unicorn
addons:
  apt:
    packages:
      - lib32ncurses5
      - lib32z1
      - lib32bz2-1.0
      - libevent-pthreads-2.0-5
  homebrew:
    brewfile: true
